### ISSUE TITLE
OS2.spielerprofil 0.1

### ISSUE THREAD

**Issue by Eselce** [Eselce/OS2.scripts#14]
Gibt es die erste Version davon noch irgendwo? Im Wiki fing das mit Version 0.2 an.

**Comment by opzult** [comment]
Hab die Urversion von Sebastian Klebba aus dem Thread (https://os.ongapo.com/forum/index.php?page=Thread&threadID=4409&pageNo=1&highlight=script+spielerprofil) rauskopiert und als 0.1 hochgeladen. Es gab dann noch ein schneller Folge ein paar Fehlerkorrekturen, aber das hier ist die erste Version. Und auch das allererste (öffentliche) OS2-Script.

**Comment by Eselce** [comment]
Jo, ich erinnere mich... Erledigt!
