### ISSUE TITLE
OS2.spielbericht.XXL vor 0.6

### ISSUE THREAD

**Issue by Eselce** [Eselce/OS2.scripts#15]
Gibt es zwischen OS2.spielbericht (1.0) und der XXL-Version 0.6 noch irgendwas? Im Wiki fing das mit Version 0.6 an.

**Comment by opzult** [comment]
Im Wiki habe ich nur eine V0.1 gefunden. Der Unterschied zu 1.0 ist minimal: Keine Durchschnittswerte mehr außer beim Zweikampferfolg.
Ob es zwischen V1.0 und XXL V0.6 was gibt, weiß ich nicht.
Ich versuche dann mal die 0.1 hochzuladen (mein erstes Mal). Drückt mir die Daumen...

**Comment by Eselce** [comment]
Ich laß'das mal offen für Michael wegen 1.0 (0.1) < x < 0.6... vielleicht gibt es da ja gar nichts...

**Comment by Eselce** [comment]
> [quote='Michael Bertram','index.php?page=PMView&pmID=770877#pm770877']
> 
> Die Version 0.6 ist die erste, die ich veröffentlicht habe.
> Davor war nur auf meiner Festplatte und unfertig.

**Comment by Eselce** [comment]
Erledigt.
