### ISSUE TITLE
OS2.master - @include für os_menu_haupt.html fehlt

### ISSUE THREAD

**Issue by opzult** [Eselce/OS2.scripts#25]
Ich denke im OS2.master (veröffentlichte Version 2.4+WE) fehlt das @include für die Hauptseite.
Z.B. werden die Spielereinzelwerte hervorgehoben auf Seite https://os.ongapo.com/showteam.php?s=2, aber nicht auf Seite https://os.ongapo.com/os_menu_haupt.html.

**Comment by Eselce** [comment]
Auf das Menü brauchst Du doch gar nicht reagieren...
Die Hauptseite geht allerdings nicht wegen des `@noframes`-Problem,
also daß `GM4` derzeit noch alle Seiten im `iframe` ignoriert

**Comment by Eselce** [comment]
Du meintest übrigens vermutlich, was aber funktionieren sollte, diese Seite: [https://os.ongapo.com/st.php?c=273&s=2](https://os.ongapo.com/st.php?c=273&s=2)
